title: AI Metallurgy
# email: your-email@example.com
description: >-
  Putting together pieces of AI
baseurl: ""
url: "https://elondemirok.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: post

# Minima skin and social links can be customized here
minima:
  skin: dark
